# Generated by Django 6.0.4 on 2026-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='sector',
            field=models.CharField(choices=[('health', 'الصحة'), ('sports', 'الرياضة'), ('education', 'التعليم'), ('tourism', 'السياحة'), ('general', 'عام')], default='general', max_length=50),
        ),
    ]
