# Generated by Django 6.0.4 on 2026-05-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_inquiry_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='sector',
            field=models.CharField(choices=[('sports', 'Sports'), ('health', 'Health'), ('education', 'Education')], max_length=50),
        ),
    ]
