# Generated by Django 6.0.4 on 2026-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_inquiry_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='sector',
            field=models.CharField(choices=[('sports', 'sports'), ('health', 'health'), ('education', 'education')], max_length=50),
        ),
    ]
