# Generated by Django 6.0.3 on 2026-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_inquiry_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='sector',
            field=models.CharField(choices=[('sports', 'Sports'), ('health', 'Health'), ('education', 'Education')], max_length=50),
        ),
    ]
