# Generated by Django 6.0.3 on 2026-06-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_inquiry_answer_inquiry_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='created_at',
        ),
    ]
