# Generated by Django 6.0.3 on 2026-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_remove_inquiry_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='sector',
            field=models.CharField(max_length=100),
        ),
    ]
