# Generated by Django 6.0.3 on 2026-06-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('month_en', models.CharField(max_length=50)),
                ('news', models.IntegerField(default=0)),
                ('events', models.IntegerField(default=0)),
                ('services', models.IntegerField(default=0)),
                ('facilities', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SectorStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('sports', 'sports'), ('health', 'health'), ('education', 'education')], max_length=20, unique=True)),
                ('news', models.IntegerField(default=0)),
                ('events', models.IntegerField(default=0)),
                ('services', models.IntegerField(default=0)),
                ('facilities', models.IntegerField(default=0)),
            ],
        ),
    ]
