# Generated by Django 6.0.4 on 2026-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.CharField(blank=True, choices=[('sports', 'الرياضة'), ('health', 'الصحة'), ('education', 'التعليم')], max_length=20, null=True),
        ),
    ]
