# Generated by Django 6.0.4 on 2026-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sector',
            field=models.CharField(blank=True, choices=[('sports', 'sports'), ('health', 'health'), ('education', 'education')], max_length=20, null=True),
        ),
    ]
