# Generated by Django 6.0.3 on 2026-06-05 07:37

import media_gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ar', models.TextField(blank=True, max_length=800, null=True)),
                ('description_en', models.TextField(blank=True, max_length=800, null=True)),
                ('type', models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=10)),
                ('url', models.FileField(blank=True, null=True, upload_to='media_gallery/', validators=[media_gallery.models.validate_media_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Media Gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
