# Generated by Django 6.0.4 on 2026-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_event_sector_alter_facility_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sector',
            field=models.CharField(choices=[('sports', 'sports'), ('health', 'health'), ('education', 'education')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sector',
            field=models.CharField(choices=[('sports', 'sports'), ('health', 'health'), ('education', 'education')], max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='sector',
            field=models.CharField(choices=[('sports', 'sports'), ('health', 'health'), ('education', 'education')], max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='sector',
            field=models.CharField(choices=[('sports', 'sports'), ('health', 'health'), ('education', 'education')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='sector',
            field=models.CharField(choices=[('sports', 'sports'), ('health', 'health'), ('education', 'education')], max_length=20),
        ),
    ]
