"""
Django settings for homs project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""




from pathlib import Path 
from datetime import timedelta
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d#8o1=ler6r65#(6x5urpv)#m!&m*yp(bzf$i1clds8$s62u4g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['sandy11.pythonanywhere.com','localhost','127.0.0.1','*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'content',
    'rest_framework', 
    'corsheaders',
    'accounts',
    'comments',
    'media_gallery',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


""""" 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'homshub_new',      # The name of the DB you created in Postgres
        'USER': 'postgres',      # Your database username
        'PASSWORD': '1234',  # Your database password
        'HOST': '127.0.0.1',         # Set to server IP for remote databases
        'PORT': '5432',              # Default PostgreSQL port
    }}
"""

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'homshub_db',  # اسم القاعدة التي سننشئها في XAMPP بعد قليل
        'USER': 'root',        # اسم المستخدم الافتراضي لبرنامج XAMPP
        'PASSWORD': '',        # اتركيها فارغة تماماً بدون أي مسافة بين علامتي التنصيص
        'HOST': '127.0.0.1',   # تعني السيرفر المحلي على جهازك
        'PORT': '3306',        # المنفذ الافتراضي لـ MySQL
    }
}
"""
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'neondb',      # The name of the DB you created in Postgres
        'USER': 'neondb_owner',      # Your database username
        'PASSWORD': 'npg_JvW7BhqwOn5R',  # Your database password
        'HOST': 'ep-gentle-feather-aqr99qeh-pooler.c-8.us-east-1.aws.neon.tech',         # Set to server IP for remote databases
        'PORT': '5432',              # Default PostgreSQL port
        'OPTIONS': {
            'sslmode': 'requir',
        },
    }}
    """
    
   
   
   
   
   
   
    

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True




 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


AUTH_USER_MODEL = "accounts.User"





REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # مدة صلاحية التوكن (للتطوير جعلناها يوماً)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # للمستخدمين غير المسجلين
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/day', # يسمح بـ 5 رسائل فقط في اليوم لكل شخص (يمكنك تغييرها)
    }
}


#الربط الذي سيتخدمه الفرونت اند للوصول للصورة 
MEDIA_URL ='api/media/'
#المكان الحقيقي على الهارد ديسك الذي ستحفظ فيه الملفات 
MEDIA_ROOT= os.path.join(BASE_DIR, 'media/')



CORS_ALLOW_ALL_ORIGINS =True




